In [16]:
import numpy as np

In [17]:
data = [
    [9, 30, 14, 29, 11, 32, 10, 31, 8, 32, 15, 30, 7, 27],
    [13, 32, 9, 30, 13, 23, -13, 28, 9, 24, 6, 29, 12, 20],
    [14, 27, 10, 28, 6, 27, 12, 20, 14, 26, 8, 30, 7, 30],
    [11, 28, 6, 24, 9, 26, 13, 23, 13, 22, 14, 21, 15, 28],
    [11, 29, 6, 20, 6, 25, 12, 31, 12, 27, 14, 23, 12, 24],
    [12, 32, 6, 30, 10, 20, 7, 29, 7, 29, 9, 23, 15, 25],
    [14, 30, 10, 28, 12, 24, 13, 25, 14, 28, 15, 32, 7, 27],
    [6, 21, 8, 23, 6, 20, 10, 30, 9, 29, 9, 26, 14, 25],
    [5, 21, 8, 21, 7, 20, 8, 18, 3, 18, 8, 4, 19, 7],
    [7, 21, 7, 22, 4, 19, 5, 18, 7, 19, 2, 5, 20, 6],
    [4, 22, 2, 22, 5, 18, 7, 20, 7, 19, 4, 3, 21, 8],
    [5, 18, 5, 20, 4, 18, 3, 19, 7, 20, 7, 3, 19, 7],
    [12, 18, 9, 21, -10, 21, 8, 20, 8, 20, 11, 71, 19, 8],
    [7, 21, 9, 22, 12, 22, 7, 18, 11, 20, 8, 10, 19, 10],
    [12, 22, 8, 21, 12, 22, 10, 19, 7, 20, 12, 9, 19, 7],
    [7, 19, 10, 19, 8, 19, 9, 19, 11, 18, 12, 8, 22, 9]
]

# 1. Represent the data in the given sheet into an appropriate NumPy array so
that you can perform the following actions on it.


In [18]:
data = np.array(data)

In [19]:
data

array([[  9,  30,  14,  29,  11,  32,  10,  31,   8,  32,  15,  30,   7,
         27],
       [ 13,  32,   9,  30,  13,  23, -13,  28,   9,  24,   6,  29,  12,
         20],
       [ 14,  27,  10,  28,   6,  27,  12,  20,  14,  26,   8,  30,   7,
         30],
       [ 11,  28,   6,  24,   9,  26,  13,  23,  13,  22,  14,  21,  15,
         28],
       [ 11,  29,   6,  20,   6,  25,  12,  31,  12,  27,  14,  23,  12,
         24],
       [ 12,  32,   6,  30,  10,  20,   7,  29,   7,  29,   9,  23,  15,
         25],
       [ 14,  30,  10,  28,  12,  24,  13,  25,  14,  28,  15,  32,   7,
         27],
       [  6,  21,   8,  23,   6,  20,  10,  30,   9,  29,   9,  26,  14,
         25],
       [  5,  21,   8,  21,   7,  20,   8,  18,   3,  18,   8,   4,  19,
          7],
       [  7,  21,   7,  22,   4,  19,   5,  18,   7,  19,   2,   5,  20,
          6],
       [  4,  22,   2,  22,   5,  18,   7,  20,   7,  19,   4,   3,  21,
          8],
       [  5,  18,   5,  20,   4,  18,   3, 

# Write the dimensions and shape of the NumPy array that you have
created

In [20]:
data.shape

(16, 14)

In [21]:
data.ndim

2

# Print the daily temperatures for the first week of each month.


In [22]:
nn = np.size(data, axis=0)

In [23]:
nn

16

In [24]:
for i in range(nn):
    if(i%4==0):
        print(data[i])

[ 9 30 14 29 11 32 10 31  8 32 15 30  7 27]
[11 29  6 20  6 25 12 31 12 27 14 23 12 24]
[ 5 21  8 21  7 20  8 18  3 18  8  4 19  7]
[ 12  18   9  21 -10  21   8  20   8  20  11  71  19   8]


# Print the temperatures for Tuesday of each month.


In [25]:
numpy_array = np.array(data)

tue_min_col = 4
tue_max_col = 5

# Extract temperatures for Tuesday from each month
for month_data in numpy_array:
    month = month_data[0]  # Assuming the first column is the month name
    tue_min_temp = month_data[tue_min_col]
    tue_max_temp = month_data[tue_max_col]
    
    print(f"Month: {month}, Tuesday Min Temp: {tue_min_temp}, Tuesday Max Temp: {tue_max_temp}")

Month: 9, Tuesday Min Temp: 11, Tuesday Max Temp: 32
Month: 13, Tuesday Min Temp: 13, Tuesday Max Temp: 23
Month: 14, Tuesday Min Temp: 6, Tuesday Max Temp: 27
Month: 11, Tuesday Min Temp: 9, Tuesday Max Temp: 26
Month: 11, Tuesday Min Temp: 6, Tuesday Max Temp: 25
Month: 12, Tuesday Min Temp: 10, Tuesday Max Temp: 20
Month: 14, Tuesday Min Temp: 12, Tuesday Max Temp: 24
Month: 6, Tuesday Min Temp: 6, Tuesday Max Temp: 20
Month: 5, Tuesday Min Temp: 7, Tuesday Max Temp: 20
Month: 7, Tuesday Min Temp: 4, Tuesday Max Temp: 19
Month: 4, Tuesday Min Temp: 5, Tuesday Max Temp: 18
Month: 5, Tuesday Min Temp: 4, Tuesday Max Temp: 18
Month: 12, Tuesday Min Temp: -10, Tuesday Max Temp: 21
Month: 7, Tuesday Min Temp: 12, Tuesday Max Temp: 22
Month: 12, Tuesday Min Temp: 12, Tuesday Max Temp: 22
Month: 7, Tuesday Min Temp: 8, Tuesday Max Temp: 19


# Print only the maximum temperature for all the weekdays of Dec and Feb.

In [26]:
max_temp_columns = {
    "Mon": 2,
    "Tue": 4,
    "Wed": 6,
    "Thu": 8,
    "Fri": 10,
    "Sat": 12,
    "Sun": 14
}

# Months you're interested in
months_of_interest = ["December", "February"]

# Iterate through the array and print maximum temperatures for weekdays of Dec and Feb
for month_data in numpy_array:
    month = month_data[0]
    
    if month in months_of_interest:
        for weekday, col_idx in max_temp_columns.items():
            max_temp = month_data[col_idx]
            print(f"Month: {month}, Weekday: {weekday}, Max Temp: {max_temp}")

In [27]:
min_temp_columns = {
    "Mon": 1,
    "Tue": 3,
    "Wed": 5,
    "Thu": 7,
    "Fri": 9,
    "Sat": 11,
    "Sun": 13
}

# Iterate through the array and print days with minimum temperature < 8 degrees in November
for month_data in numpy_array:
    month = month_data[0]
    if month == "November":
        week = month_data[1]
        for weekday, col_idx in min_temp_columns.items():
            min_temp = month_data[col_idx]
            if min_temp < 8:
                print(f"Month: {month}, Week: {week}, Weekday: {weekday}, Min Temp: {min_temp}")

In [28]:
max_temp_columns = {
    "Mon": 2,
    "Tue": 4,
    "Wed": 6,
    "Thu": 8,
    "Fri": 10,
    "Sat": 12,
    "Sun": 14
}

# Threshold for maximum temperature
temperature_threshold = 20

# Iterate through the array and print weeks with maximum temperature > threshold
for month_data in numpy_array:
    month = month_data[0]
    if month in ["December", "January"]:
        week = month_data[1]
        week_max_temps = [month_data[col_idx] for col_idx in max_temp_columns.values()]
        
        if any(temp > temperature_threshold for temp in week_max_temps):
            print(f"Month: {month}, Week: {week}")


In [29]:
min_reasonable_temp = -100  # Example: unrealistically low
max_reasonable_temp = 100   # Example: unrealistically high

# Iterate through the array and check for absurd temperature values
for month_data in numpy_array:
    for temp in month_data:
        if temp < min_reasonable_temp or temp > max_reasonable_temp:
            print(f"Absurd value detected: {temp}")

In [30]:
outlier_threshold = 40  # Example threshold

# Find and print indexes of outlier values
outlier_indexes = np.where(numpy_array > outlier_threshold)
print("Indexes of Outliers:", outlier_indexes)

Indexes of Outliers: (array([12], dtype=int64), array([11], dtype=int64))


In [31]:
outlier_threshold = 40  # Example threshold

# Replace outliers with the median value
median_value = np.median(numpy_array)
numpy_array[numpy_array > outlier_threshold] = median_value

# Print the modified array
print("Modified Array:")
print(numpy_array)

Modified Array:
[[  9  30  14  29  11  32  10  31   8  32  15  30   7  27]
 [ 13  32   9  30  13  23 -13  28   9  24   6  29  12  20]
 [ 14  27  10  28   6  27  12  20  14  26   8  30   7  30]
 [ 11  28   6  24   9  26  13  23  13  22  14  21  15  28]
 [ 11  29   6  20   6  25  12  31  12  27  14  23  12  24]
 [ 12  32   6  30  10  20   7  29   7  29   9  23  15  25]
 [ 14  30  10  28  12  24  13  25  14  28  15  32   7  27]
 [  6  21   8  23   6  20  10  30   9  29   9  26  14  25]
 [  5  21   8  21   7  20   8  18   3  18   8   4  19   7]
 [  7  21   7  22   4  19   5  18   7  19   2   5  20   6]
 [  4  22   2  22   5  18   7  20   7  19   4   3  21   8]
 [  5  18   5  20   4  18   3  19   7  20   7   3  19   7]
 [ 12  18   9  21 -10  21   8  20   8  20  11  14  19   8]
 [  7  21   9  22  12  22   7  18  11  20   8  10  19  10]
 [ 12  22   8  21  12  22  10  19   7  20  12   9  19   7]
 [  7  19  10  19   8  19   9  19  11  18  12   8  22   9]]


In [33]:
month_indices = {
    "January": 1,
    "February": 2,
    "December": 12
}

# Extract data for the winter months (December, January, February)
winter_data = numpy_array[np.isin(numpy_array[:, 0], list(month_indices.values()))]

# Calculate the average maximum temperature for the winter months
average_max_temp = np.mean(winter_data[:, [10, 12]])  # Max temp column indices: 10, 12

print("Average Max Temperature for Winter Months in Jaipur:", average_max_temp)


Average Max Temperature for Winter Months in Jaipur: 14.166666666666666


In [34]:
month_indices = {
    "December": 12
}

# Extract data for the month of December
december_data = numpy_array[numpy_array[:, 0] == month_indices["December"]]

# Calculate weekly minimum average temperature for December
weeks = np.unique(december_data[:, 1])  # Assuming week numbers are in the second column
weekly_min_avg_temps = []

for week in weeks:
    week_data = december_data[december_data[:, 1] == week]
    weekly_min_avg_temp = np.mean(week_data[:, 8])  # Min temp column index: 8
    weekly_min_avg_temps.append((week, weekly_min_avg_temp))

print("Weekly Minimum Average Temperatures for December in Jaipur:")
for week, temp in weekly_min_avg_temps:
    print(f"Week {int(week)}:", temp)

Weekly Minimum Average Temperatures for December in Jaipur:
Week 18: 8.0
Week 22: 7.0
Week 32: 7.0


In [35]:
month_indices = {
    "December": 12,
    "January": 1
}

# Extract data for the months of December and January
dec_jan_data = numpy_array[np.isin(numpy_array[:, 0], list(month_indices.values()))]

# Calculate the overall average temperature for Dec and Jan
overall_avg_temp = np.mean(dec_jan_data[:, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]])

print("Overall Average Temperature for December and January:", overall_avg_temp)

Overall Average Temperature for December and January: 14.583333333333334


In [36]:
month_indices = {
    "December": 12,
    "January": 1
}

# Initialize variables to track the minimum temperature and its date
min_temp = np.inf  # Initialize with a very large value
min_temp_date = None

# Iterate through the data and find the least temperature in Dec and Jan
for row in numpy_array:
    month = row[0]
    if month in month_indices.values():
        min_temp_candidate = min(row[2:14])  # Minimum temperature columns
        if min_temp_candidate < min_temp:
            min_temp = min_temp_candidate
            min_temp_date = row

# Print the least temperature and its date
print("Least Temperature:", min_temp)
print("Date (Month/Week/Day):", min_temp_date[0], min_temp_date[1], min_temp_date[2])

Least Temperature: -10
Date (Month/Week/Day): 12 18 9


In [38]:
month_indices = {
    "November": 11,
    "December": 12,
    "January": 1,
    "February": 2
}

# Create an empty list to store the rearranged rows
rearranged_data = []

# Iterate through the month indices and rearrange the data
for month in month_indices.values():
    month_data = numpy_array[numpy_array[:, 0] == month]
    rearranged_data.append(month_data)

# Stack the rearranged data vertically
final_rearranged_data = np.vstack(rearranged_data)

# Print the rearranged data
print("Rearranged Data:")
print(final_rearranged_data)

Rearranged Data:
[[ 11  28   6  24   9  26  13  23  13  22  14  21  15  28]
 [ 11  29   6  20   6  25  12  31  12  27  14  23  12  24]
 [ 12  32   6  30  10  20   7  29   7  29   9  23  15  25]
 [ 12  18   9  21 -10  21   8  20   8  20  11  14  19   8]
 [ 12  22   8  21  12  22  10  19   7  20  12   9  19   7]]


In [43]:
month_indices = {
    "November": 11,
    "December": 12,
    "January": 1,
    "February": 2
}

# Iterate through the data and calculate differences for each month
differences = []

for month in month_indices.values():
    month_data = numpy_array[numpy_array[:, 0] == month]
    max_temps = month_data[:, 2:14:2]  # Maximum temperatures for each day
    temp_diffs = np.diff(max_temps, axis=1)  # Calculate differences between consecutive days
    differences.append(temp_diffs)

# Stack the differences vertically
differences_array = np.vstack(differences)

# Print the differences array
print("Differences between Max Temperatures of Consecutive Days:")
print(differences_array)

Differences between Max Temperatures of Consecutive Days:
[[  3   4   0   1   1]
 [  0   6   0   2  -2]
 [  4  -3   0   2   6]
 [-19  18   0   3   8]
 [  4  -2  -3   5   7]]
